'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {buildWindowDeltaAudit}=require('../scripts/audit_institutional_accumulation_catalyst_prospective_window_deltas');
const {buildCrossDayAudit}=require('../scripts/audit_institutional_accumulation_catalyst_prospective_cross_day_window');
const {buildFourthWindowLongitudinalAudit}=require('../scripts/audit_institutional_accumulation_catalyst_prospective_fourth_window_longitudinal');
const {buildFifthWindowLongitudinalAudit}=require('../scripts/audit_institutional_accumulation_catalyst_prospective_fifth_window_longitudinal');
const ROOT='data_research/institutional-flow/official-disclosure-raw/prospective-catalyst-pit';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
test('sixth window preserves all previously closed deterministic artifacts',()=>{
  const delta=buildWindowDeltaAudit(process.cwd(),{rootRelative:ROOT,skipCommittedAuditCheck:true});
  const cross=buildCrossDayAudit(process.cwd(),{rootRelative:ROOT});
  const fourth=buildFourthWindowLongitudinalAudit(process.cwd(),{rootRelative:ROOT});
  const fifth=buildFifthWindowLongitudinalAudit(process.cwd(),{rootRelative:ROOT});
  assert.deepEqual(delta,read('data_research/institutional-flow/institutional-accumulation-catalyst-prospective-window-delta-audit-v1.json'));
  assert.deepEqual(cross,read('data_research/institutional-flow/institutional-accumulation-catalyst-prospective-cross-day-audit-v1.json'));
  assert.deepEqual(fourth,read('data_research/institutional-flow/institutional-accumulation-catalyst-prospective-fourth-window-longitudinal-audit-v1.json'));
  assert.deepEqual(fifth,read('data_research/institutional-flow/institutional-accumulation-catalyst-prospective-fifth-window-longitudinal-audit-v1.json'));
});
