#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const DIR=path.join(ROOT,'data_prediction_analysis','eps-valuation');
const VAL=path.join(DIR,'valuation-backtest.json');
const POL=path.join(DIR,'valuation-applicability-policy.json');
const OUT=path.join(DIR,'formula-selection-study.json');
const OUTMD=path.join(DIR,'formula-selection-study.md');
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'));}
function round(v,d=2){return Number.isFinite(v)?Number(v.toFixed(d)):null;}
function q(xs,p){const a=xs.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const z=(a.length-1)*p,l=Math.floor(z),h=Math.ceil(z);return l===h?a[l]:a[l]+(a[h]-a[l])*(z-l);}
function policyFilter(policy){const ex=new Set(policy?.yoy_scaled_remaining?.excluded_event_keys||[]);const dyn=new Set(policy?.dynamic_pe?.methods||[]);const cap=Number(policy?.dynamic_pe?.max_pe);return r=>{if(r.eps_method==='yoy_scaled_remaining'&&ex.has(`${r.stock_code}:${r.fiscal_period}`))return false;if(dyn.has(r.pe_method)&&Number.isFinite(cap)){const lo=Number(r.pe_low),hi=Number(r.pe_high);if(!(lo>0)||!(hi>0)||Math.max(lo,hi)>cap)return false;}return true;};}
function summarize(rows){const g=new Map();for(const r of rows){const k=`${r.eps_method}__${r.pe_method}`;if(!g.has(k))g.set(k,[]);g.get(k).push(r);}return [...g.entries()].map(([formula,a])=>{const re=a.map(x=>Number(x.range_error_pct)).filter(Number.isFinite);const ce=a.map(x=>Number(x.center_error_pct)).filter(Number.isFinite);return{formula,eps_method:a[0].eps_method,eps_method_label:a[0].eps_method_label,pe_method:a[0].pe_method,pe_method_label:a[0].pe_method_label,stocks:new Set(a.map(x=>x.stock_code)).size,events:new Set(a.map(x=>`${x.stock_code}:${x.fiscal_period}`)).size,samples:a.length,hit_rate_pct:round(a.filter(x=>x.hit_range).length/a.length*100),median_range_error_pct:round(q(re,.5)),p90_range_error_pct:round(q(re,.9)),p95_range_error_pct:round(q(re,.95)),p99_range_error_pct:round(q(re,.99)),mean_range_error_pct:round(re.reduce((s,x)=>s+x,0)/re.length),median_center_error_pct:round(q(ce,.5)),structural_baseline:a[0].eps_method==='ttm'&&a[0].pe_method==='current_pe20'};});}
function rankScore(r){return (r.median_range_error_pct||0)*.45+(r.p95_range_error_pct||0)*.30+(r.median_center_error_pct||0)*.15+(100-(r.hit_rate_pct||0))*.10;}
function main(){const val=read(VAL),pol=read(POL);const rows=val.rows.filter(policyFilter(pol));const all=summarize(rows);for(const r of all)r.robust_score=round(rankScore(r));all.sort((a,b)=>a.robust_score-b.robust_score||b.samples-a.samples);
 const nonBaseline=all.filter(x=>!x.structural_baseline);const bestScore=nonBaseline[0]?.robust_score||0;for(const r of all){if(r.structural_baseline)r.recommendation='benchmark_only';else if(r.robust_score<=bestScore*1.18&&r.samples>=1800)r.recommendation='keep_core';else if(r.robust_score<=bestScore*1.45&&r.samples>=1500)r.recommendation='keep_secondary';else r.recommendation='drop_or_baseline';}
 const byEps={};for(const em of [...new Set(all.map(x=>x.eps_method))]){const a=all.filter(x=>x.eps_method===em&&!x.structural_baseline);byEps[em]={label:a[0]?.eps_method_label||em,median_robust_score:round(q(a.map(x=>x.robust_score),.5)),median_hit_rate_pct:round(q(a.map(x=>x.hit_rate_pct),.5)),median_p95_error_pct:round(q(a.map(x=>x.p95_range_error_pct),.5)),core_count:a.filter(x=>x.recommendation==='keep_core').length};}
 const byPe={};for(const pm of [...new Set(all.map(x=>x.pe_method))]){const a=all.filter(x=>x.pe_method===pm&&!x.structural_baseline);byPe[pm]={label:a[0]?.pe_method_label||pm,median_robust_score:round(q(a.map(x=>x.robust_score),.5)),median_hit_rate_pct:round(q(a.map(x=>x.hit_rate_pct),.5)),median_p95_error_pct:round(q(a.map(x=>x.p95_range_error_pct),.5)),core_count:a.filter(x=>x.recommendation==='keep_core').length};}
 const out={schema_version:1,dataset:'eps_formula_selection_study',generated_at:new Date().toISOString(),source_generated_at:val.generated_at||null,policy_generated_at:pol.generated_at||null,filtered_samples:rows.length,formula_count:all.length,ranking_rule:'robust_score = 45% median range error + 30% P95 range error + 15% median center error + 10% miss-rate. Lower is better. TTM × current TTM P/E is flagged benchmark_only because it algebraically collapses to current price ±20%.',formulas:all,by_eps_method:byEps,by_pe_method:byPe};fs.writeFileSync(OUT,JSON.stringify(out,null,2)+'\n');
 const md=['# EPS 24 套公式保留研究','',`產生時間：${out.generated_at}`,'',`Guard 後樣本：${rows.length}`,'','|排名|EPS 法|P/E 法|樣本|命中率%|Median Range%|P95 Range%|Median Center%|Robust score|建議|','|---:|---|---|---:|---:|---:|---:|---:|---:|---|'];all.forEach((r,i)=>md.push(`|${i+1}|${r.eps_method_label}|${r.pe_method_label}|${r.samples}|${r.hit_rate_pct}|${r.median_range_error_pct}|${r.p95_range_error_pct}|${r.median_center_error_pct}|${r.robust_score}|${r.recommendation}|`));md.push('','> TTM × 事件日 TTM P/E ±20% 僅保留為價格基準，不視為獨立 EPS 估值模型。','');fs.writeFileSync(OUTMD,md.join('\n'));
 console.log(JSON.stringify({output:path.relative(ROOT,OUT),samples:rows.length,top:all.slice(0,10)},null,2));}
if(require.main===module){try{main();}catch(e){console.error(e.stack||e.message);process.exitCode=1;}}
