#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const getArg = (name, fallback) => { const i = args.indexOf(`--${name}`); return i >= 0 && args[i + 1] ? args[i + 1] : fallback; };
const input = getArg('input', path.join('data_research','institutional-flow','backtests','institutional-withdrawal-v6-distribution-absorption.json'));
const output = getArg('output', path.join('data_research','institutional-flow','backtests','institutional-withdrawal-v6-1-event-diagnosis.json'));
const report = getArg('report', path.join('data_research','institutional-flow','backtests','institutional-withdrawal-v6-1-event-diagnosis.md'));
const p = JSON.parse(fs.readFileSync(input, 'utf8'));
const all = p.results?.all_eligible?.events || [];
const fragile = all.filter((e) => e.classification?.structure === 'fragile_distribution');
const byStock = new Map();
for (const e of all) { if (!byStock.has(e.stock)) byStock.set(e.stock, []); byStock.get(e.stock).push(e); }
for (const arr of byStock.values()) arr.sort((a,b)=>a.tdcc_observed_date.localeCompare(b.tdcc_observed_date));
const round = (v,d=2)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
function history(stock,date,n=4){ const arr=byStock.get(stock)||[]; const i=arr.findIndex(e=>e.tdcc_observed_date===date); return i<0?[]:arr.slice(Math.max(0,i-n+1),i+1).map(e=>({date:e.tdcc_observed_date,large_holder_pct:e.tdcc?.large_holder_pct,small_holder_pct:e.tdcc?.small_holder_pct,large_change_1obs_pp:e.tdcc?.large_change_1obs_pp,small_change_1obs_pp:e.tdcc?.small_change_1obs_pp,transfer_streak:e.tdcc?.transfer_streak,broker_score:e.broker?.score,foreign_net_5d:e.foreign?.net_5d,foreign_sell_ratio_5d:e.foreign?.sell_ratio_5d,return_5d_into_anchor_pct:e.price_volume?.return_5d_pct,volume_ratio_20d:e.price_volume?.volume_ratio_20d,distribution_days_10d:e.price_volume?.distribution_days_10d,absorption_days_10d:e.price_volume?.absorption_days_10d,structure:e.classification?.structure})); }
function outcomeDiagnosis(e){ const o=e.outcome||{}; const r5=o.return_5d_pct, r10=o.return_10d_pct, r20=o.return_20d_pct, dd=o.max_drawdown_20d_pct, gain=o.max_gain_20d_pct; let label='insufficient_followup'; if (Number.isFinite(r20)) { if (r20<=-5 || (Number.isFinite(dd)&&dd<=-10)) label='persistent_withdrawal_consistent'; else if (r20>5 && (!Number.isFinite(dd)||dd>-10)) label='absorbed_or_false_positive'; else label='mixed'; } else if (Number.isFinite(r10)) { if (r10<=-5 || (Number.isFinite(dd)&&dd<=-10)) label='short_horizon_withdrawal_consistent'; else if (r10>5) label='short_horizon_absorbed'; else label='mixed_short_horizon'; } return {label,return_5d_pct:r5,return_10d_pct:r10,return_20d_pct:r20,max_drawdown_20d_pct:dd,max_gain_20d_pct:gain}; }
function evidenceStrength(e){ let s=0; if((e.tdcc?.transfer_streak||0)>=2)s++; if((e.tdcc?.large_change_2obs_pp||0)<=-1)s++; if((e.foreign?.net_5d||0)<0 && (e.foreign?.sell_ratio_5d||0)>=0.6)s++; if((e.broker?.score||0)>=3)s++; if((e.price_volume?.return_5d_pct||0)<=0)s++; if((e.price_volume?.close_vs_prior_20d_high_pct||0)<=-5)s++; return s; }
const events=fragile.map(e=>({stock:e.stock,anchor:e.tdcc_observed_date,pre_anchor_history:history(e.stock,e.tdcc_observed_date,4),evidence:{tdcc:e.tdcc,broker:e.broker,foreign:e.foreign,price_volume:e.price_volume},evidence_strength:evidenceStrength(e),outcome:outcomeDiagnosis(e)}));
const classifications={}; for(const e of events) classifications[e.outcome.label]=(classifications[e.outcome.label]||0)+1;
const kyec=(byStock.get('2449')||[]).map(e=>({date:e.tdcc_observed_date,structure:e.classification?.structure,persistent_transfer:e.classification?.persistent_transfer,broker_pressure:e.classification?.broker_pressure,large_holder_pct:e.tdcc?.large_holder_pct,small_holder_pct:e.tdcc?.small_holder_pct,large_change_2obs_pp:e.tdcc?.large_change_2obs_pp,small_change_2obs_pp:e.tdcc?.small_change_2obs_pp,transfer_streak:e.tdcc?.transfer_streak,broker_score:e.broker?.score,foreign_net_5d:e.foreign?.net_5d,foreign_sell_ratio_5d:e.foreign?.sell_ratio_5d,return_5d_into_anchor_pct:e.price_volume?.return_5d_pct,volume_ratio_20d:e.price_volume?.volume_ratio_20d,close_vs_prior_20d_high_pct:e.price_volume?.close_vs_prior_20d_high_pct,outcome:outcomeDiagnosis(e)}));
const firstKyecPersistent=kyec.find(x=>x.persistent_transfer);
const firstKyecFragile=kyec.find(x=>x.structure==='fragile_distribution');
const payload={schema_version:1,methodology:'institutional-withdrawal-v6-1-event-diagnosis-v1',research_only:true,production_safe:false,source_methodology:p.methodology,fragile_event_count:events.length,outcome_classification_counts:classifications,events,kyec_2449:{first_persistent_transfer_date:firstKyecPersistent?.date||null,first_fragile_distribution_date:firstKyecFragile?.date||null,timeline:kyec,interpretation:'Lead time is relative to later disclosures only if an externally verified disclosure date is supplied; this research output does not infer or fabricate that date.'},guardrails:['v6 classifications are frozen; v6.1 does not change thresholds.','Future outcomes are used only for diagnosis, never to construct event features.','Broker branches do not identify beneficial owners.','Historical TDCC original publication timestamps remain unknown, so this is association research rather than executable historical P&L.'],generated_at:new Date().toISOString()};
fs.mkdirSync(path.dirname(output),{recursive:true}); fs.writeFileSync(output,JSON.stringify(payload,null,2)+'\n');
const lines=['# Institutional Withdrawal v6.1 — Event Diagnosis','',`- Fragile distribution events: **${events.length}**`,`- Outcome labels: ${Object.entries(classifications).map(([k,v])=>`${k}=${v}`).join(', ')}`,'','## Event table','','| Stock | Anchor | Evidence strength | Outcome diagnosis | 5D | 10D | 20D | Max DD |','|---|---|---:|---|---:|---:|---:|---:|'];
for(const e of events) lines.push(`| ${e.stock} | ${e.anchor} | ${e.evidence_strength} | ${e.outcome.label} | ${e.outcome.return_5d_pct ?? 'n/a'}% | ${e.outcome.return_10d_pct ?? 'n/a'}% | ${e.outcome.return_20d_pct ?? 'n/a'}% | ${e.outcome.max_drawdown_20d_pct ?? 'n/a'}% |`);
lines.push('','## 2449 timeline','',`- First persistent-transfer anchor in frozen v6 sample: **${firstKyecPersistent?.date||'none'}**`,`- First fragile-distribution anchor in frozen v6 sample: **${firstKyecFragile?.date||'none'}**`,'','| Date | Structure | Transfer streak | Large 2obs Δ | Small 2obs Δ | Broker | Foreign 5D | Sell ratio | Price 5D into anchor | 20D outcome |','|---|---|---:|---:|---:|---:|---:|---:|---:|---:|');
for(const x of kyec) lines.push(`| ${x.date} | ${x.structure} | ${x.transfer_streak ?? 0} | ${x.large_change_2obs_pp ?? 'n/a'}pp | ${x.small_change_2obs_pp ?? 'n/a'}pp | ${x.broker_score ?? 'n/a'} | ${x.foreign_net_5d ?? 'n/a'} | ${x.foreign_sell_ratio_5d ?? 'n/a'} | ${x.return_5d_into_anchor_pct ?? 'n/a'}% | ${x.outcome.return_20d_pct ?? 'n/a'}% |`);
lines.push('','## Interpretation','', '- `fragile_distribution` is best treated as a state-transition candidate: persistent ownership transfer plus broker supply with weak contemporaneous absorption.', '- Event-level outcome labels are descriptive diagnostics only; they do not alter the frozen v6 rules.', '- A later public disclosure date must be independently verified before claiming the signal led that disclosure by N days.');
fs.writeFileSync(report,lines.join('\n')+'\n');
console.log(JSON.stringify({fragile_event_count:events.length,outcome_classification_counts:classifications,first_2449_persistent:firstKyecPersistent?.date||null,first_2449_fragile:firstKyecFragile?.date||null},null,2));
