#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),PRED=path.join(ROOT,'data_predictions'),OUT=path.join(ROOT,'data_prediction_analysis','relative-leadership');
const TARGET='relative_leadership',MAX_DATES=30,MIN_N=5,MAX_K=4;
const read=(f,d=null)=>{try{const t=fs.readFileSync(f,'utf8').trim();return t?JSON.parse(t):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof v==='string'?v:`${JSON.stringify(v,null,2)}\n`)};
const compact=v=>String(v||'').replaceAll('-','').replaceAll('/','');
const finite=v=>Number.isFinite(Number(v))?Number(v):null;
const round=(v,d=2)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
const rate=(a,b)=>b?a/b*100:null;
const wilson=(h,n,z=1.96)=>{if(!n)return null;const p=h/n,den=1+z*z/n,c=p+z*z/(2*n),m=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n);return (c-m)/den*100};
const get=(o,p)=>p.split('.').reduce((v,k)=>v==null?undefined:v[k],o);
const has=(o,p)=>{for(const k of p.split('.')){if(o==null||!Object.prototype.hasOwnProperty.call(o,k))return false;o=o[k]}return true};
function args(){const a={};for(let i=2;i<process.argv.length;i++){if(process.argv[i]==='--date')a.date=compact(process.argv[++i]);if(process.argv[i]==='--max-dates')a.max=Number(process.argv[++i])}return a}
function dates(limit){return fs.readdirSync(PRED).filter(x=>/^20\d{6}$/.test(x)).filter(x=>['summary.json','replay-dashboard.json'].every(f=>fs.existsSync(path.join(PRED,x,f)))).sort().slice(-limit)}
function load(date){const dir=path.join(PRED,date),s=read(path.join(dir,'summary.json'),{stocks:[]}),r=read(path.join(dir,'replay-dashboard.json'),{rows:[]}),m=new Map(r.rows.map(x=>[String(x.stock_code),x]));return s.stocks.map(p=>{const q=m.get(String(p.stock_code));return{date,code:String(p.stock_code),name:p.stock_name,industry:p.industry,p,q,target:q?.market_relative?.classification===TARGET,verified:Boolean(q?.verified)}}).filter(x=>x.verified)}
function atoms(byDate){const out=[];const exact=(fam,label,p,val)=>out.push({id:`${fam}= ${val}`,fam,label:`${label}＝${val}`,avail:r=>has(r.p,p),test:r=>get(r.p,p)===val});const truth=(fam,label,p)=>out.push({id:fam,fam,label,avail:r=>has(r.p,p),test:r=>Boolean(get(r.p,p))});const th=(fam,label,p,vals,dirs)=>dirs.forEach(d=>vals.forEach(v=>out.push({id:`${fam}:${d}:${v}`,fam,label:`${label} ${d==='g'?'>=':'<='} ${v}`,avail:r=>finite(get(r.p,p))!=null,test:r=>{const n=finite(get(r.p,p));return n!=null&&(d==='g'?n>=v:n<=v)}})));
['中性偏多','中性','中性偏空'].forEach(v=>exact('direction','方向','final_direction_label',v));['低風險','中風險','高風險'].forEach(v=>exact('risk','風險','risk_label',v));['偏多','偏空','中性或不足'].forEach(v=>exact('chip','籌碼','chip_bias',v));['大盤跌勢抗跌','大盤漲勢領先','大盤跌勢弱勢','大盤漲勢落後'].forEach(v=>exact('rsmode','7日RS型態','relative_strength_7d.relative_strength_mode',v));
truth('rsstrong','7日相對強勢成立','relative_strength_7d.relative_strength_strong');[['sma20','收復SMA20','reversal_signals.crossed_sma20'],['sma60','收復SMA60','reversal_signals.crossed_sma60'],['macdx','MACD黃金交叉','reversal_signals.macd_bullish_cross'],['macdturn','MACD柱翻正','reversal_signals.macd_histogram_positive_turn'],['kdx','KD黃金交叉','reversal_signals.kd_bullish_cross'],['kdturn','KD低檔轉強','reversal_signals.kd_oversold_turn']].forEach(x=>truth(...x));
const all=[...byDate.values()].flat(),tags=[...new Set(all.flatMap(r=>r.p.strategy_tags||[]))];for(const tag of tags)out.push({id:`tag:${tag}`,fam:`tag:${tag}`,label:`策略：${tag}`,type:'tag',avail:()=>true,test:r=>(r.p.strategy_tags||[]).includes(tag)});
[['score','方向分數','direction_score',[-4,-3,-2,-1,0,1,2,3,4]],['r1','r1','features.r1',[-5,-3,-1,0,1,2,3,5]],['r3','r3','features.r3',[-10,-5,-3,0,2,5,8,12]],['v1','1日量比','features.volume_ratio_1d',[.7,1,1.2,1.5,2,3]],['v5','5日量比','features.volume_ratio_5d',[.8,1,1.2,1.5,2]],['gap','SMA20乖離','features.gap_sma20',[-10,-5,0,5,10,15]],['rsi','RSI14','features.rsi14',[25,30,35,40,50,55,60,65,70]],['inst','法人比','features.institutional_ratio',[0,2,5,10,20]],['main','主力比','features.main_net_ratio',[-5,0,1,2,5,10]],['margin','融資變化率','features.margin_change_rate',[-5,-2,0,2,5]],['rs7','7日RS','relative_strength_7d.relative_strength_7d',[-5,0,2,5,8,10,15]],['ret7','個股7日報酬','relative_strength_7d.stock_return_7d',[-5,-2,0,2,5,8,12]],['mh','MACD柱','reversal_signals.macd_histogram',[-.5,0,.2,.5]],['k9','K9','reversal_signals.k9',[20,30,50,70,80]]].forEach(x=>th(...x,['g','l']));
out.push({id:'kaboved',fam:'kdrel',label:'K9 >= D9',avail:r=>finite(r.p.reversal_signals?.k9)!=null&&finite(r.p.reversal_signals?.d9)!=null,test:r=>finite(r.p.reversal_signals?.k9)>=finite(r.p.reversal_signals?.d9)});
for(const a of out){a.available={};a.selected={};for(const[d,rows]of byDate){a.available[d]=round(rate(rows.filter(a.avail).length,rows.length));a.selected[d]=rows.filter(a.test).length}a.common=Object.values(a.available).every(x=>x>=95)&&(a.type!=='tag'||Object.values(a.selected).every(x=>x>0))}return out}
function sum(rows,base){const h=rows.filter(x=>x.target).length,p=rate(h,rows.length);return{count:rows.length,hits:h,precision:round(p),lift:p!=null&&base?round(p/base,2):null,wilson_lower_95:round(wilson(h,rows.length))}}
function evalRule(as,dev,valid){const sel=rows=>rows.filter(r=>as.every(a=>a.test(r))),db=rate(dev.filter(r=>r.target).length,dev.length),ds=sel(dev),all=[],per=[];for(const[d,rows]of valid){const s=sel(rows);all.push(...s);per.push({date:d,...sum(s,rate(rows.filter(r=>r.target).length,rows.length))})}const vr=[...valid.values()].flat(),v=sum(all,rate(vr.filter(r=>r.target).length,vr.length));v.day_count=per.filter(x=>x.count).length;v.per_date=per;return{atoms:as,discovery:sum(ds,db),validation:v,devRows:ds,valRows:all}}
const dscore=c=>(c.discovery.precision||0)*2+(c.discovery.wilson_lower_95||0)*2+Math.min(c.discovery.count,40)*.7+4/c.atoms.length;
const vscore=c=>(c.validation.precision||0)*2+(c.validation.wilson_lower_95||0)*3+Math.min(c.validation.count,50)+c.validation.day_count*15+(c.discovery.precision||0)*.4;
function search(dev,valid,as){let beam=as.map((a,i)=>({...evalRule([a],dev,valid),idx:[i]})).filter(c=>c.discovery.count>=MIN_N).sort((a,b)=>dscore(b)-dscore(a)).slice(0,160),found=[...beam];for(let k=2;k<=MAX_K;k++){const next=[],seen=new Set;for(const p of beam){const last=p.idx.at(-1),fams=new Set(p.atoms.map(a=>a.fam));for(let i=last+1;i<as.length;i++){if(fams.has(as[i].fam))continue;const idx=[...p.idx,i],key=idx.join();if(seen.has(key))continue;seen.add(key);const c={...evalRule([...p.atoms,as[i]],dev,valid),idx};if(c.discovery.count>=MIN_N&&(c.discovery.precision||0)>=15)next.push(c)}}next.sort((a,b)=>dscore(b)-dscore(a));beam=next.slice(0,k===2?1000:k===3?700:400);found.push(...beam)}const u=new Map;for(const c of found){const key=c.devRows.map(r=>r.code).sort().join();const old=u.get(key);if(!old||c.atoms.length<old.atoms.length||dscore(c)>dscore(old))u.set(key,c)}return[...u.values()]}
function tier(c){const d=c.discovery,v=c.validation;if(d.count>=5&&d.precision>=90&&v.count>=8&&v.precision>=80&&v.day_count>=2)return'A';if(d.count>=8&&d.precision>=70&&v.count>=12&&v.precision>=65&&v.day_count>=2)return'B';if(d.count>=12&&d.precision>=50&&v.count>=20&&v.precision>=45&&v.day_count>=3)return'C';return null}
const stocks=rows=>rows.map(r=>({date:r.date,stock_code:r.code,stock_name:r.name,industry:r.industry,relative_leadership:r.target}));
const ser=(c,t)=>({tier:t,conditions:c.atoms.map(a=>a.label),condition_ids:c.atoms.map(a=>a.id),discovery:c.discovery,validation:c.validation,discovery_stocks:stocks(c.devRows),validation_stocks:stocks(c.valRows)});
function md(p){const L=[`# 相對領漲共同欄位研究：${p.discovery_date}`,'',`- 探索日：${p.discovery_date}` ,`- 驗證日：${p.validation_dates.join('、')}` ,`- 探索基準率：${p.discovery_baseline.precision}%（${p.discovery_baseline.hits}/${p.discovery_baseline.count}）`,`- 驗證基準率：${p.validation_baseline.precision}%（${p.validation_baseline.hits}/${p.validation_baseline.count}）`,'',`- A級 ${p.tier_counts.A} 組；B級 ${p.tier_counts.B} 組；C級 ${p.tier_counts.C} 組。`,`- 07/30 至少5檔且命中>=90%的共同欄位規則：${p.discovery_near_perfect_rules.length} 組。`,'','## 跨日候選','','|級別|條件|07/30命中|樣本|前期命中|樣本|涵蓋日|95%下限|','|---|---|---:|---:|---:|---:|---:|---:|'];for(const r of p.stable_rules.slice(0,20))L.push(`|${r.tier}|${r.conditions.join(' ＋ ')}|${r.discovery.precision}%|${r.discovery.count}|${r.validation.precision}%|${r.validation.count}|${r.validation.day_count}|${r.validation.wilson_lower_95}%|`);if(!p.stable_rules.length)L.push('|—|目前沒有達門檻規則|—|—|—|—|—|—|');L.push('','## 最佳共同欄位探索規則','','|條件|07/30命中|樣本|前期命中|樣本|涵蓋日|','|---|---:|---:|---:|---:|---:|');for(const r of p.best_common_rules.slice(0,20))L.push(`|${r.conditions.join(' ＋ ')}|${r.discovery.precision}%|${r.discovery.count}|${r.validation.precision}%|${r.validation.count}|${r.validation.day_count}|`);L.push('','> 只使用四天都有的事前欄位；不使用股票身分、產業或結果日資訊。大量組合測試仍可能過度擬合，需累積更多覆盤日。');return L.join('\n')+'\n'}
function main(){const a=args(),max=Number.isFinite(a.max)?Math.max(2,Math.min(30,Math.floor(a.max))):MAX_DATES,ds=dates(max),devDate=a.date||ds.at(-1),use=ds.filter(d=>d<=devDate),by=new Map(use.map(d=>[d,load(d)])),dev=by.get(devDate),valid=new Map([...by].filter(([d])=>d<devDate)),allAtoms=atoms(by),common=allAtoms.filter(a=>a.common),cand=search(dev,valid,common),stable=cand.map(c=>({c,t:tier(c)})).filter(x=>x.t).sort((a,b)=>((({A:0,B:1,C:2})[a.t]-({A:0,B:1,C:2})[b.t])||vscore(b.c)-vscore(a.c))),near=cand.filter(c=>c.discovery.count>=5&&c.discovery.precision>=90).sort((a,b)=>b.discovery.precision-a.discovery.precision||b.discovery.wilson_lower_95-a.discovery.wilson_lower_95),best=cand.filter(c=>c.validation.count>=8&&c.validation.day_count>=2).sort((a,b)=>vscore(b)-vscore(a)),vr=[...valid.values()].flat(),db=rate(dev.filter(r=>r.target).length,dev.length),vb=rate(vr.filter(r=>r.target).length,vr.length),p={schema_version:'3.0.0',generated_at:new Date().toISOString(),target:TARGET,discovery_date:devDate,validation_dates:[...valid.keys()],available_dates:use,max_dates:max,methodology:{max_conditions:MAX_K,minimum_discovery_support:MIN_N,common_fields_only:true,common_requirement:'>=95% available every date; strategy tag appears every date',leakage_controls:['prediction-time only','no stock identity','no industry','no result-day inputs']},discovery_baseline:sum(dev,db),validation_baseline:sum(vr,vb),atom_count:allAtoms.length,common_atom_count:common.length,candidate_count:cand.length,tier_counts:{A:stable.filter(x=>x.t==='A').length,B:stable.filter(x=>x.t==='B').length,C:stable.filter(x=>x.t==='C').length},stable_rules:stable.slice(0,50).map(x=>ser(x.c,x.t)),discovery_near_perfect_rules:near.slice(0,50).map(c=>ser(c,'discovery_only')),best_common_rules:best.slice(0,50).map(c=>ser(c,'exploratory_common')),field_availability:allAtoms.map(a=>({id:a.id,label:a.label,common:a.common,availability_by_date:a.available,selection_by_date:a.selected}))};write(path.join(OUT,`${devDate}.json`),p);write(path.join(OUT,`${devDate}.md`),md(p));write(path.join(OUT,'manifest.json'),{generated_at:p.generated_at,schema_version:p.schema_version,latest_date:devDate,available_dates:use,latest_json:`data_prediction_analysis/relative-leadership/${devDate}.json`,latest_markdown:`data_prediction_analysis/relative-leadership/${devDate}.md`});console.log(JSON.stringify({dates:use,rows:Object.fromEntries([...by].map(([d,r])=>[d,r.length])),atoms:allAtoms.length,common:common.length,candidates:cand.length,tiers:p.tier_counts,near:near.length},null,2))}
try{main()}catch(e){console.error(e.stack||e.message);process.exit(1)}
