'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DAILY_GAINERS_AI_CONTRACT:CONTRACT,isLatestNews,isLatestPublished}=require('./lib/daily_gainers_ai_contract');
const ROOT=path.resolve(__dirname,'..'),DATA=path.join(ROOT,'data_daily_gain_over_5'),OUT=path.join(DATA,'market-summary'),TAX=path.join(ROOT,'config','daily-gainers-theme-taxonomy.json');
function args(v){const a={date:'',previousDate:'',force:false,selfTest:false};for(let i=0;i<v.length;i++){if(v[i]==='--date')a.date=v[++i]||'';else if(v[i]==='--previous-date')a.previousDate=v[++i]||'';else if(v[i]==='--force')a.force=true;else if(v[i]==='--self-test')a.selfTest=true;else throw new Error(`Unknown argument: ${v[i]}`)}return a}
function read(f,opt=false){if(!f||!fs.existsSync(f)){if(opt)return null;throw new Error(`Missing required file: ${f}`)}return JSON.parse(fs.readFileSync(f,'utf8'))}
function sha(f){return f&&fs.existsSync(f)?crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'):null}
function rel(f){return f?path.relative(ROOT,f).split(path.sep).join('/'):null}
function desc(f,x={}){return{path:rel(f),available:Boolean(f&&fs.existsSync(f)),sha256:sha(f),...x}}
function n(v){if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null}
function round(v,d=1){if(!Number.isFinite(v))return null;const f=10**d;return Math.round(v*f)/f}
function pct(c,t){return t>0?round(c/t*100,1):0}
function code(v){return String(v??'').trim()}
function taxonomy(){const p=read(TAX),alias=new Map(),labels=new Map();for(const t of p.themes||[]){labels.set(t.id,t.label);for(const a of [t.id,...(t.aliases||[])])alias.set(String(a).toLowerCase(),t.id)}return{p,alias,labels}}
function themesOf(a,t){const xs=[];if(typeof a?.primary_theme==='string')xs.push(a.primary_theme);if(Array.isArray(a?.theme_tags))xs.push(...a.theme_tags);if(Array.isArray(a?.cause_tags))xs.push(...a.cause_tags);const out=[];for(const x of xs){const id=t.alias.get(String(x).trim().toLowerCase());if(id&&!out.includes(id))out.push(id)}return out}
function themeSummary(rows,analyses,t){const by=new Map(analyses.map(x=>[code(x.code),x])),b=new Map();let covered=0;for(const r of rows){const id=themesOf(by.get(code(r.code)),t)[0];if(!id)continue;covered++;if(!b.has(id))b.set(id,[]);b.get(id).push(r)}const ranking=[...b].map(([id,m])=>{const gs=m.map(x=>n(x.change_pct)).filter(x=>x!==null),count=m.length;return{theme_id:id,label:t.labels.get(id)||id,stock_count:count,share_pct:pct(count,rows.length),near_limit_up_count:m.filter(x=>(n(x.change_pct)??-Infinity)>=9.5).length,average_gain_pct:round(gs.length?gs.reduce((a,b)=>a+b,0)/gs.length:null,2),strength:count>=5?'very_strong':count>=3?'strong':count===2?'moderate':'isolated',representative_stocks:m.slice().sort((a,b)=>(n(b.change_pct)??-Infinity)-(n(a.change_pct)??-Infinity)).slice(0,5).map(x=>code(x.code))}}).sort((a,b)=>b.stock_count-a.stock_count||(b.average_gain_pct||0)-(a.average_gain_pct||0));return{taxonomy_version:t.p.methodology_version,themed_stock_count:covered,unclassified_stock_count:rows.length-covered,theme_coverage_pct:pct(covered,rows.length),theme_ranking:ranking,top_1_theme_share_pct:pct(ranking[0]?.stock_count||0,rows.length),top_3_theme_share_pct:pct(ranking.slice(0,3).reduce((s,x)=>s+x.stock_count,0),rows.length)}}
function catalysts(analyses,total){const c={direct:0,corroborated:0,circumstantial:0,none:0,unavailable:0},types={};for(const a of analyses){const k=Object.hasOwn(c,a.evidence_strength)?a.evidence_strength:'unavailable';c[k]++;const t=a.cause_type||'unknown';types[t]=(types[t]||0)+1}c.unavailable+=Math.max(0,total-analyses.length);const publicCount=c.direct+c.corroborated;return{...c,public_catalyst_count:publicCount,public_catalyst_coverage_pct:pct(publicCount,total),cause_type_counts:types}}
function funding(analyses,total){let sup=0,opp=0,inc=0,dec=0,avail=0,ia=0,ma=0;for(const a of analyses){const f=a.flow||{},nets=['foreign','investment_trust','dealer'].map(k=>n(f[k]?.net_lots)).filter(x=>x!==null),m=n(f.margin?.margin_delta);if(nets.length)ia++;if(m!==null)ma++;if(nets.length||m!==null)avail++;const net=nets.reduce((s,x)=>s+x,0);if(nets.length&&net>0)sup++;if(nets.length&&net<0)opp++;if(m!==null&&m>0)inc++;if(m!==null&&m<0)dec++}return{coverage_status:avail===total&&total>0?'complete':avail>0?'partial':'missing',available_stock_count:avail,institutional_available_stock_count:ia,margin_available_stock_count:ma,institutional_support_count:sup,institutional_opposition_count:opp,margin_increase_count:inc,margin_decrease_count:dec}}
function regime(raw,t){const count=(raw.stocks||[]).length;if(!count)return'unknown';if(count>=40&&t.top_3_theme_share_pct<45)return'broad_risk_on';if(t.top_3_theme_share_pct>=45&&t.theme_ranking.length>=2)return'theme_rotation';if(count>=25)return'mixed';return'risk_off_with_pockets'}
function narrative(raw,t,c,f,stage,semantic){const total=(raw.stocks||[]).length,top=t.theme_ranking.slice(0,3),topText=top.length?top.map(x=>`${x.label} ${x.stock_count} 檔`).join('、'):'題材結構仍待新聞分析';const headline=top.length?`${total} 檔強勢股，${top[0].label}為主要聚焦題材`:`${total} 檔強勢股，新聞題材分析尚待完成`;const fund=stage==='news_theme'?'籌碼階段尚未開始，待晚間 facts 與 AI synthesis 後升級。':f.coverage_status==='missing'?'籌碼資料不足，缺值未視為 0。':`已有 ${f.available_stock_count}/${total} 檔可判讀籌碼，法人偏多 ${f.institutional_support_count} 檔。`;const cat=semantic?`公開直接或交叉佐證催化覆蓋 ${c.public_catalyst_coverage_pct}%。`:'新聞語意資料尚未完成，不將缺資料顯示成 0%。';const summary=`本日共有 ${total} 檔股票漲幅達 5% 以上；${topText}。${cat}${fund}`;const watch=[];if(top[0])watch.push(`觀察 ${top[0].label} 是否續量並維持族群擴散。`);if(semantic&&c.none+c.circumstantial>c.public_catalyst_count)watch.push('弱證據個股占比較高，留意隔日動能退潮。');if(stage==='news_theme')watch.push('晚間補上法人、融資、券商與技術後，確認題材是否有資金結構支持。');else if(f.coverage_status!=='complete')watch.push('待籌碼資料完整後，再確認法人與融資是否支持本日強勢結構。');if(!watch.length)watch.push('觀察強勢股廣度、成交量與法人籌碼是否延續。');return{headline,summary,watch}}
function build(date,prevOverride=''){if(!/^\d{8}$/.test(date))throw new Error('--date must be YYYYMMDD');const rawPath=path.join(DATA,`${date}.json`),newsPath=path.join(DATA,'analysis-news',`${date}.json`),factsPath=path.join(DATA,'analysis-facts',`${date}.json`),finalPath=path.join(DATA,'analysis',`${date}.json`);const raw=read(rawPath),rows=Array.isArray(raw.stocks)?raw.stocks:[];if(String(raw.target_date)!==date)throw new Error('raw target_date mismatch');
 const news=read(newsPath,true),final=read(finalPath,true),facts=read(factsPath,true);const latestNews=isLatestNews(news)&&String(news?.target_date)===date,latestFinal=isLatestPublished(final)&&String(final?.target_date)===date;const rawCodes=rows.map(x=>code(x.code));const newsAnalyses=latestNews&&Array.isArray(news.analyses)?news.analyses:[],finalAnalyses=latestFinal&&Array.isArray(final.analyses)?final.analyses:[];const exact=(xs)=>xs.length===rawCodes.length&&xs.every((x,i)=>code(x.code)===rawCodes[i]);const exactNews=latestNews&&exact(newsAnalyses),exactFinal=latestFinal&&exact(finalAnalyses);const stage=exactFinal?'full_synthesis':'news_theme',semantic=exactFinal?finalAnalyses:exactNews?newsAnalyses:[];
 const previousDate=prevOverride||String(raw.previous_date||'');if(previousDate&&(!/^\d{8}$/.test(previousDate)||previousDate>=date))throw new Error('invalid previous_date');const prevPath=previousDate?path.join(DATA,`${previousDate}.json`):null,prev=prevPath?read(prevPath,true):null;
 const tax=taxonomy(),ts=themeSummary(rows,semantic,tax);ts.market_structure=regime(raw,ts);const cat=catalysts(semantic,rows.length),fund=stage==='full_synthesis'?funding(finalAnalyses,rows.length):funding([],rows.length),g=rows.map(x=>n(x.change_pct));if(g.some(x=>x===null||x<5))throw new Error('invalid raw change_pct');const breadth={stock_count:rows.length,gain_5_to_7_count:g.filter(x=>x>=5&&x<7).length,gain_7_to_9_5_count:g.filter(x=>x>=7&&x<9.5).length,gain_9_5_plus_count:g.filter(x=>x>=9.5).length,previous_day_stock_count:prev&&Array.isArray(prev.stocks)?prev.stocks.length:null,stock_count_change:prev&&Array.isArray(prev.stocks)?rows.length-prev.stocks.length:null};const nav=narrative(raw,ts,cat,fund,stage,semantic.length>0),risk=[];if(semantic.length&&cat.none+cat.circumstantial>cat.public_catalyst_count)risk.push('weak_catalyst_coverage');if(ts.top_1_theme_share_pct>=35)risk.push('high_theme_concentration');if(stage==='full_synthesis'&&fund.coverage_status!=='complete')risk.push('funding_coverage_incomplete');if(!exactNews&&!exactFinal)risk.push('news_semantic_coverage_incomplete');
 return{schema_version:CONTRACT.market_summary.schema_version,methodology_version:CONTRACT.market_summary.methodology_version,contract_version:CONTRACT.contract_version,target_date:date,previous_date:previousDate||null,generated_at:new Date().toISOString(),status:exactFinal?'final':'preliminary',summary_stage:stage,source_lineage:{raw:desc(rawPath),previous_raw:desc(prevPath),news:desc(newsPath,{latest_contract:latestNews}),facts:desc(factsPath),analysis:desc(finalPath,{latest_contract:latestFinal}),theme_taxonomy:desc(TAX),semantic_source:exactFinal?'published_unified_analysis':exactNews?'news_theme_analysis':'none'},coverage:{overall:exactFinal?'complete':exactNews?'partial':'missing',raw:'complete',previous_raw:prev?'complete':'missing',news:exactNews?'complete':'missing',facts:facts?'complete':'missing',analysis:exactFinal?'complete':'missing',funding:fund.coverage_status,analyzed_stock_count:semantic.length,raw_stock_count:rows.length},breadth,market_context:{regime:ts.market_structure,source:exactFinal?final.market_context||null:null},theme_summary:ts,catalyst_coverage:cat,funding_summary:fund,risk_signals:risk,headline:nav.headline,market_summary:nav.summary,next_day_watch:nav.watch}}
function stripped(p){const x=JSON.parse(JSON.stringify(p));delete x.generated_at;return x}
function manifest(s){fs.mkdirSync(OUT,{recursive:true});const f=path.join(OUT,'manifest.json'),old=read(f,true),dates=new Set(old?.dates||[]);dates.add(s.target_date);const ds=[...dates].filter(x=>/^\d{8}$/.test(x)).sort().reverse(),body={schema_version:2,methodology_version:CONTRACT.market_summary.methodology_version,latest_date:ds[0]||null,dates:ds};if(old&&JSON.stringify(stripped(old))===JSON.stringify(body))return false;fs.writeFileSync(f,JSON.stringify({...body,generated_at:new Date().toISOString()},null,2)+'\n');return true}
function self(){const t=taxonomy(),rows=[{code:'1',change_pct:9.7},{code:'2',change_pct:8}],a=[{code:'1',cause_tags:['pcb'],evidence_strength:'direct'},{code:'2',cause_tags:['pcb'],evidence_strength:'none'}];if(themeSummary(rows,a,t).theme_ranking[0]?.stock_count!==2)throw new Error('theme self-test');if(catalysts(a,2).public_catalyst_count!==1)throw new Error('catalyst self-test');if(funding([{flow:{foreign:{net_lots:null},margin:{margin_delta:null}}}],1).coverage_status!=='missing')throw new Error('funding null self-test');console.log('build_daily_gainers_market_summary self-test passed')}
function main(){const a=args(process.argv.slice(2));if(a.selfTest)return self();const s=build(a.date,a.previousDate),f=path.join(OUT,`${a.date}.json`),old=read(f,true);let changed=true;if(!a.force&&old&&JSON.stringify(stripped(old))===JSON.stringify(stripped(s))){changed=false;console.log(`Market summary unchanged for ${a.date}`)}else{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(f,JSON.stringify(s,null,2)+'\n')}const mc=manifest(changed?s:old);console.log(JSON.stringify({output:rel(f),summary_changed:changed,manifest_changed:mc,status:s.status,summary_stage:s.summary_stage,coverage:s.coverage,breadth:s.breadth},null,2))}
if(require.main===module)main();
