#!/usr/bin/env node
'use strict';
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'data_research/institutional-flow/official-disclosure-raw/mops-material-information/preflight.json');
const API_ENDPOINT = 'https://mops.twse.com.tw/mops/api/t05st01';
const API_CONTRACT_VERSION = 'mops-api-t05st01-json-v1';
const LEGACY_ENDPOINT = 'https://mops.twse.com.tw/mops/web/ajax_t05st01';
const LEGACY_CONTRACT_VERSION = 'mops-web-ajax-t05st01-form-v1';
const REQUEST_BODY = Object.freeze({ companyId: '1102', year: '115', month: 'all', firstDay: '', lastDay: '' });
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function sha(b){return crypto.createHash('sha256').update(b).digest('hex');}
function successfulMessage(m){return /查詢成功|成功|success/i.test(String(m||''));}
function valueType(v){return v===null?'null':Array.isArray(v)?'array':typeof v==='object'?'object':typeof v;}
function findDetailDescriptors(value){const out=[];function visit(n,p){if(!n||typeof n!=='object')return;if(!Array.isArray(n)&&n.apiName==='t05st01_detail'&&n.parameters&&['enterDate','serialNumber','companyId','marketKind'].every(k=>Object.prototype.hasOwnProperty.call(n.parameters,k)))out.push({path:p,apiName:n.apiName,parameters:Object.fromEntries(['enterDate','serialNumber','companyId','marketKind'].map(k=>[k,String(n.parameters[k]??'')]))});if(Array.isArray(n))n.forEach((x,i)=>visit(x,`${p}[${i}]`));else Object.entries(n).forEach(([k,x])=>visit(x,`${p}.${k}`));}visit(value,'$');return out;}
function rowShapeDiagnostics(rows){if(!Array.isArray(rows))return{coherent:false,reason:'result_data_not_array'};if(rows.length===0)return{coherent:true,reason:'empty_array_observed',row_type:'empty'};const types=rows.map(valueType);if(new Set(types).size!==1)return{coherent:false,reason:'mixed_top_level_row_types',row_type_counts:Object.fromEntries([...new Set(types)].map(t=>[t,types.filter(x=>x===t).length]))};if(types[0]==='array'){const lengths=[...new Set(rows.map(r=>r.length))];const max=Math.max(...rows.map(r=>r.length));const cols=Array.from({length:max},(_,i)=>[...new Set(rows.map(r=>valueType(r[i])))].sort());return{coherent:lengths.length===1&&cols.every(x=>x.length===1),reason:'observed_array_rows',row_type:'array',row_lengths:lengths,column_type_sets:cols};}if(types[0]==='object'){const sig=[...new Set(rows.map(r=>Object.keys(r).sort().join('|')))];return{coherent:sig.length===1,reason:'observed_object_rows',row_type:'object',object_key_signatures:sig};}return{coherent:false,reason:'unsupported_row_type',row_type:types[0]};}
function analyzeListingPayload(payload){const rows=Array.isArray(payload?.result?.data)?payload.result.data:null;const descriptors=rows?findDetailDescriptors(rows):[];const shape=rowShapeDiagnostics(rows);const ok=String(payload?.code)==='200'&&successfulMessage(payload?.message)&&String(payload?.result?.companyId??'')==='1102'&&rows!==null&&shape.coherent&&(rows.length===0||descriptors.length>0);return{application_code:payload?.code??null,application_message:payload?.message??null,application_success:String(payload?.code)==='200'&&successfulMessage(payload?.message),company_id_matches:String(payload?.result?.companyId??'')==='1102',result_data_is_array:rows!==null,row_count:rows?.length??null,coherent_row_structure:shape.coherent,row_shape:shape,detail_descriptor_count:descriptors.length,detail_descriptor_locations:descriptors.map(d=>d.path),sample_detail_descriptor:descriptors[0]?{apiName:descriptors[0].apiName,parameters:descriptors[0].parameters}:null,listing_contract_passed:ok,exact_empty_data_contract_observed:Boolean(rows&&rows.length===0)};}
function legacyEvidence(existing){return existing?.contracts?.legacy||{contract_version:LEGACY_CONTRACT_VERSION,endpoint:LEGACY_ENDPOINT,method:'POST',attempt_count:Number(existing?.attempt_count||0),retryable:existing?.retryable===true,terminal_state:existing?.terminal_state??null,requests:existing?.diagnostics?.requests||[]};}
async function main(){const existing=JSON.parse(fs.readFileSync(OUT,'utf8'));const legacy=legacyEvidence(existing);if(legacy.attempt_count!==2||legacy.retryable!==true||legacy.terminal_state!==null)throw new Error('Legacy baseline changed');await sleep(2000+Math.floor(Math.random()*3001));const r=await fetch(API_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0 (compatible; stock-data-row-shape-preflight/1.0)','accept':'application/json, text/plain, */*'},body:JSON.stringify(REQUEST_BODY)});const bytes=Buffer.from(await r.arrayBuffer());const text=new TextDecoder('utf-8').decode(bytes);let json=null,parseError=null;try{json=JSON.parse(text);}catch(e){parseError=e.message;}const a=json?analyzeListingPayload(json):{application_code:null,application_message:null,application_success:false,company_id_matches:false,result_data_is_array:false,row_count:null,coherent_row_structure:false,row_shape:{coherent:false,reason:'malformed_json'},detail_descriptor_count:0,detail_descriptor_locations:[],sample_detail_descriptor:null,listing_contract_passed:false,exact_empty_data_contract_observed:false};const decision=r.status===200&&!parseError&&a.listing_contract_passed?'listing_contract_passed_detail_contract_unproven':'corrected_api_contract_blocked';const result={schema_version:2,methodology:'institutional-accumulation-material-information-row-shape-detail-contract-preflight-v1',outcome_blind:true,started_at:new Date().toISOString(),completed_at:new Date().toISOString(),decision,reason:a.listing_contract_passed?'corrected_api_listing_contract_verified_detail_method_url_body_not_proven':'corrected_api_listing_schema_or_transport_blocked',retryable:false,terminal_state:null,contracts:{legacy,corrected_api:{contract_version:API_CONTRACT_VERSION,endpoint:API_ENDPOINT,method:'POST',request_body:REQUEST_BODY,attempt_count:1,request_cap_this_round:3,requests_used_this_round:1,listing_request:{status:r.status,final_url:r.url,bytes:bytes.length,sha256:sha(bytes),parseable_json:json!==null,parse_error:parseError},...a,detail_contract:{status:'unproven',request_executed:false,rationale:'apiName alone is insufficient to guess detail HTTP contract.'},transient_raw_response_text:text}},diagnostics:{stock:'1102',roc_year:'115',request_cap:3,total_network_requests_this_round:1,collection_time_is_pit_proof:false}};fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));}
if(require.main===module)main().catch(e=>{console.error(e.stack||e.message);process.exitCode=1;});
module.exports={API_ENDPOINT,API_CONTRACT_VERSION,LEGACY_ENDPOINT,LEGACY_CONTRACT_VERSION,REQUEST_BODY,successfulMessage,findDetailDescriptors,rowShapeDiagnostics,analyzeListingPayload,legacyEvidence};
