#!/usr/bin/env node
'use strict';
const fs=require('node:fs'); const path=require('node:path');
const {getDailyPrice,clearCaches,loadFromHistorySma,loadFromLegacyFubon,loadFromTwseMiIndex}=require('./lib/stock_price_provider');
const {scoreComponents}=require('./summarize_mops_revenue_fundamental_acceleration_score');
const {latestKnownFinancial}=require('./summarize_two_stage_fundamental_quality_long_horizons');
const ROOT=path.resolve(__dirname,'..');
const SIGNAL_ROOT=path.join(ROOT,'data_prediction_analysis','monthly-revenue','monthly-signals');
const REVENUE_ROOT=path.join(ROOT,'data_mops_monthly_revenue');
const MASTER_FILE=path.join(ROOT,'data_prediction_analysis','quarterly-financial-quality','financial-quality-master.json');
const MARKET_FILE=path.join(ROOT,'data_twse_market_chart','market_chart.json');
const OUTPUT=path.join(ROOT,'data_prediction_analysis','quarterly-financial-quality','two-stage-fundamental-quality-pullback-predictors.json');
const PRICE_LOADERS=[loadFromHistorySma,loadFromLegacyFubon,loadFromTwseMiIndex];
const ELECTRONIC=new Set(['半導體業','電腦及週邊設備業','光電業','通信網路業','電子零組件業','電子通路業','資訊服務業','其他電子業','電子工業']);
const round=(v,d=4)=>Number.isFinite(v)?Number(v.toFixed(d)):null; const mean=a=>{a=a.filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null};
function readJson(f,x=null){try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return x;}}
function parseArgs(argv){const m=new Map();for(let i=0;i<argv.length;i++)if(argv[i].startsWith('--'))m.set(argv[i].slice(2),argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true);return m;}
function prevMonth(month,n=1){let y=+month.slice(0,4),m=+month.slice(4,6);while(n--){if(--m===0){m=12;y--;}}return `${y}${String(m).padStart(2,'0')}`;}
function loadRevenue(start,end){const needStart=prevMonth(start,11),byMonth=new Map(),byStock=new Map();for(const e of fs.readdirSync(REVENUE_ROOT,{withFileTypes:true}).filter(e=>e.isDirectory()&&/^20\d{4}$/.test(e.name)&&e.name>=needStart&&e.name<=end)){const p=readJson(path.join(REVENUE_ROOT,e.name,'monthly_revenue.json'),{}),mm=new Map();for(const r of p.companies||[]){const id=String(r.stock_code);mm.set(id,r);if(!byStock.has(id))byStock.set(id,new Map());byStock.get(id).set(e.name,r);}byMonth.set(e.name,mm);}return{byMonth,byStock};}
function loadFinancial(){const p=readJson(MASTER_FILE);if(!p?.stocks)throw new Error('Missing financial master');return new Map(p.stocks.map(s=>[String(s.stock_id),s.rows||[]]));}
function marketRows(){const p=readJson(MARKET_FILE,{});return(p.data||[]).filter(r=>/^20\d{6}$/.test(String(r.date))&&Number.isFinite(+r.close)).map(r=>({date:String(r.date),close:+r.close})).sort((a,b)=>a.date.localeCompare(b.date));}
function getP(id,d){return getDailyPrice(id,d,{root:ROOT,loaders:PRICE_LOADERS});}
function stockFeatures(id,idx,rows){const closes=[];for(let j=idx-20;j<=idx;j++){if(j<0)return null;const p=getP(id,rows[j].date);if(!p?.close)return null;closes.push(+p.close);}const c=closes.at(-1),r5=(c/closes[15]-1)*100,r20=(c/closes[0]-1)*100,rets=[];for(let i=1;i<closes.length;i++)rets.push(closes[i]/closes[i-1]-1);const mu=mean(rets);const vol=Math.sqrt(mean(rets.map(x=>(x-mu)**2)))*Math.sqrt(20)*100;const hi=Math.max(...closes.slice(0,20));return{pre5_return_pct:r5,pre20_return_pct:r20,pre20_vol_pct:vol,dist_from_20d_high_pct:(c/hi-1)*100};}
function marketFeature(idx,rows){if(idx<20)return null;return(rows[idx].close/rows[idx-20].close-1)*100;}
function hitPullback(id,baseIdx,baseClose,threshold,rows){for(let k=1;k<=20;k++){const d=rows[baseIdx+k]?.date;if(!d)return false;const p=getP(id,d);if(Number.isFinite(p?.low)&&p.low<=baseClose*threshold)return true;}return false;}
function quantileBins(events,key){const vals=events.map(e=>e.features[key]).filter(Number.isFinite).sort((a,b)=>a-b);if(vals.length<20)return[];const q=p=>vals[Math.min(vals.length-1,Math.floor((vals.length-1)*p))];const cuts=[q(.2),q(.4),q(.6),q(.8)];const groups=[[],[],[],[],[]];for(const e of events){const v=e.features[key];if(!Number.isFinite(v))continue;let b=0;while(b<cuts.length&&v>cuts[b])b++;groups[b].push(e);}return groups.map((g,i)=>({bin:i+1,min:round(Math.min(...g.map(x=>x.features[key]))),max:round(Math.max(...g.map(x=>x.features[key]))),samples:g.length,pullback_5_rate_pct:g.length?round(g.filter(x=>x.pb5).length/g.length*100):null,pullback_10_rate_pct:g.length?round(g.filter(x=>x.pb10).length/g.length*100):null}));}
function main(argv=process.argv.slice(2)){const args=parseArgs(argv),start=args.get('start-month')||'202401',end=args.get('end-month')||'202606';const rev=loadRevenue(start,end),fin=loadFinancial(),mr=marketRows(),idxMap=new Map(mr.map((r,i)=>[r.date,i]));const events=[];const diag={electronic_fas8_events:0,missing_known_financial:0,financial_below_10:0,included:0,missing_price_features:0};for(const f of fs.readdirSync(SIGNAL_ROOT).filter(n=>/^20\d{4}\.json$/.test(n)).sort()){const m=f.slice(0,6);if(m<start||m>end)continue;const p=readJson(path.join(SIGNAL_ROOT,f),{}),rm=rev.byMonth.get(m)||new Map();for(const ev of p.events||[]){const id=String(ev.stock_code),rr=rm.get(id)||{};if(!ELECTRONIC.has(rr.industry||'未分類'))continue;const fas=scoreComponents(ev,m,rev.byStock.get(id));if(+fas.total_score<8)continue;diag.electronic_fas8_events++;const ed=ev.effective_trading_date||ev.conservative_availability_date;const fq=latestKnownFinancial(fin.get(id)||[],ed);if(!fq||!Number.isFinite(+fq.financial_quality_score)){diag.missing_known_financial++;continue;}if(+fq.financial_quality_score<10){diag.financial_below_10++;continue;}const bd=ev.base_trading_date,idx=idxMap.get(bd),base=getP(id,bd);if(!Number.isInteger(idx)||!base?.close||!mr[idx+20]){diag.missing_price_features++;continue;}const sf=stockFeatures(id,idx,mr);if(!sf){diag.missing_price_features++;continue;}const features={fas_total:+fas.total_score,fas_yoy:+fas.yoy_score,fas_mom:+fas.mom_score,fas_acceleration:+fas.acceleration_score,fas_revenue_high:+fas.revenue_high_score,fas_persistence:+fas.persistence_score,fq_score:+fq.financial_quality_score,...sf,market_pre20_return_pct:marketFeature(idx,mr)};events.push({month:m,stock_id:id,base_trading_date:bd,features,pb5:hitPullback(id,idx,+base.close,.95,mr),pb10:hitPullback(id,idx,+base.close,.90,mr)});diag.included++;if(events.length%20===0)clearCaches();}}
clearCaches();const keys=['fas_total','fas_yoy','fas_mom','fas_acceleration','fas_revenue_high','fas_persistence','fq_score','pre5_return_pct','pre20_return_pct','pre20_vol_pct','dist_from_20d_high_pct','market_pre20_return_pct'];const factors=keys.map(k=>{const bins=quantileBins(events,k);const rates5=bins.map(b=>b.pullback_5_rate_pct).filter(Number.isFinite),rates10=bins.map(b=>b.pullback_10_rate_pct).filter(Number.isFinite);return{factor:k,bins,spread_pb5_pp:rates5.length?round(Math.max(...rates5)-Math.min(...rates5)):null,spread_pb10_pp:rates10.length?round(Math.max(...rates10)-Math.min(...rates10)):null};}).sort((a,b)=>(b.spread_pb10_pp||0)-(a.spread_pb10_pp||0));const out={schema_version:1,dataset:'two_stage_fundamental_quality_pullback_predictors',generated_at:new Date().toISOString(),start_month:start,end_month:end,methodology:{status:'research_only',universe:'electronic FAS>=8 + latest-known FQ>=10',target:'within 20 trading days after signal, whether low touches -5% / -10% from base close',feature_timing:'all predictors use information known on or before base_trading_date',binning:'quintile-style equal-frequency bins; discrete score factors may have uneven/duplicate boundaries',note:'exploratory univariate screening only; not a production classifier and no in-sample threshold should be promoted without out-of-sample validation'},coverage:{candidate_events:events.length,diagnostics:diag,overall_pb5_rate_pct:round(events.filter(e=>e.pb5).length/events.length*100),overall_pb10_rate_pct:round(events.filter(e=>e.pb10).length/events.length*100)},factors};fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({output:path.relative(ROOT,OUTPUT),coverage:out.coverage,top:factors.slice(0,8).map(x=>({factor:x.factor,pb5_spread:x.spread_pb5_pp,pb10_spread:x.spread_pb10_pp}))},null,2));}
if(require.main===module){try{main();}catch(e){console.error(e.stack||e.message);process.exitCode=1;}}
