#!/usr/bin/env node
'use strict';

const fs=require('node:fs');
const path=require('node:path');
const {getDailyPrice,clearCaches,loadFromHistorySma,loadFromLegacyFubon,loadFromTwseMiIndex}=require('./lib/stock_price_provider');
const {scoreComponents}=require('./summarize_mops_revenue_fundamental_acceleration_score');
const {latestKnownFinancial}=require('./summarize_two_stage_fundamental_quality_long_horizons');

const ROOT=path.resolve(__dirname,'..');
const SIGNAL_ROOT=path.join(ROOT,'data_prediction_analysis','monthly-revenue','monthly-signals');
const REVENUE_ROOT=path.join(ROOT,'data_mops_monthly_revenue');
const MASTER_FILE=path.join(ROOT,'data_prediction_analysis','quarterly-financial-quality','financial-quality-master.json');
const MARKET_FILE=path.join(ROOT,'data_twse_market_chart','market_chart.json');
const OUTPUT=path.join(ROOT,'data_prediction_analysis','quarterly-financial-quality','two-stage-fundamental-quality-pullback-walk-forward.json');
const DOC=path.join(ROOT,'docs','two-stage-fundamental-quality-research-log.md');
const PRICE_LOADERS=[loadFromHistorySma,loadFromLegacyFubon,loadFromTwseMiIndex];
const ELECTRONIC=new Set(['半導體業','電腦及週邊設備業','光電業','通信網路業','電子零組件業','電子通路業','資訊服務業','其他電子業','電子工業']);
const FACTORS=['pre20_vol_pct','pre5_return_pct','pre20_return_pct','dist_from_20d_high_pct'];
const round=(v,d=4)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
const mean=a=>{a=a.filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null;};
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
function readJson(f,x=null){try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return x;}}
function parseArgs(argv){const m=new Map();for(let i=0;i<argv.length;i++)if(argv[i].startsWith('--'))m.set(argv[i].slice(2),argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true);return m;}
function shiftMonth(month,delta){let y=+month.slice(0,4),m=+month.slice(4,6)+delta;while(m<=0){m+=12;y--;}while(m>12){m-=12;y++;}return `${y}${String(m).padStart(2,'0')}`;}
function loadRevenue(start,end){const needStart=shiftMonth(start,-11),byMonth=new Map(),byStock=new Map();for(const e of fs.readdirSync(REVENUE_ROOT,{withFileTypes:true}).filter(e=>e.isDirectory()&&/^20\d{4}$/.test(e.name)&&e.name>=needStart&&e.name<=end)){const p=readJson(path.join(REVENUE_ROOT,e.name,'monthly_revenue.json'),{}),mm=new Map();for(const r of p.companies||[]){const id=String(r.stock_code);mm.set(id,r);if(!byStock.has(id))byStock.set(id,new Map());byStock.get(id).set(e.name,r);}byMonth.set(e.name,mm);}return{byMonth,byStock};}
function loadFinancial(){const p=readJson(MASTER_FILE);if(!p?.stocks)throw new Error('Missing financial master');return new Map(p.stocks.map(s=>[String(s.stock_id),s.rows||[]]));}
function marketRows(){const p=readJson(MARKET_FILE,{});return(p.data||[]).filter(r=>/^20\d{6}$/.test(String(r.date))&&Number.isFinite(+r.close)).map(r=>({date:String(r.date),close:+r.close})).sort((a,b)=>a.date.localeCompare(b.date));}
function getP(id,d){return getDailyPrice(id,d,{root:ROOT,loaders:PRICE_LOADERS});}
function stockFeatures(id,idx,rows){const closes=[];for(let j=idx-20;j<=idx;j++){if(j<0)return null;const p=getP(id,rows[j].date);if(!p?.close)return null;closes.push(+p.close);}const c=closes.at(-1),r5=(c/closes[15]-1)*100,r20=(c/closes[0]-1)*100,rets=[];for(let i=1;i<closes.length;i++)rets.push(closes[i]/closes[i-1]-1);const mu=mean(rets);const vol=Math.sqrt(mean(rets.map(x=>(x-mu)**2)))*Math.sqrt(20)*100;const hi=Math.max(...closes.slice(0,20));return{pre5_return_pct:r5,pre20_return_pct:r20,pre20_vol_pct:vol,dist_from_20d_high_pct:(c/hi-1)*100};}
function hitPullback(id,baseIdx,baseClose,threshold,rows){for(let k=1;k<=20;k++){const d=rows[baseIdx+k]?.date;if(!d)return false;const p=getP(id,d);if(Number.isFinite(p?.low)&&p.low<=baseClose*threshold)return true;}return false;}
function collectEvents(start,end){const rev=loadRevenue(start,end),fin=loadFinancial(),mr=marketRows(),idxMap=new Map(mr.map((r,i)=>[r.date,i]));const events=[],diag={electronic_fas8_events:0,missing_known_financial:0,financial_below_10:0,included:0,missing_price_features:0};for(const f of fs.readdirSync(SIGNAL_ROOT).filter(n=>/^20\d{4}\.json$/.test(n)).sort()){const m=f.slice(0,6);if(m<start||m>end)continue;const p=readJson(path.join(SIGNAL_ROOT,f),{}),rm=rev.byMonth.get(m)||new Map();for(const ev of p.events||[]){const id=String(ev.stock_code),rr=rm.get(id)||{};if(!ELECTRONIC.has(rr.industry||'未分類'))continue;const fas=scoreComponents(ev,m,rev.byStock.get(id));if(+fas.total_score<8)continue;diag.electronic_fas8_events++;const ed=ev.effective_trading_date||ev.conservative_availability_date;const fq=latestKnownFinancial(fin.get(id)||[],ed);if(!fq||!Number.isFinite(+fq.financial_quality_score)){diag.missing_known_financial++;continue;}if(+fq.financial_quality_score<10){diag.financial_below_10++;continue;}const bd=ev.base_trading_date,idx=idxMap.get(bd),base=getP(id,bd);if(!Number.isInteger(idx)||!base?.close||!mr[idx+20]){diag.missing_price_features++;continue;}const sf=stockFeatures(id,idx,mr);if(!sf){diag.missing_price_features++;continue;}events.push({month:m,stock_id:id,base_trading_date:bd,features:sf,pb5:hitPullback(id,idx,+base.close,.95,mr),pb10:hitPullback(id,idx,+base.close,.90,mr)});diag.included++;if(events.length%20===0)clearCaches();}}
clearCaches();return{events,diag};}
function fitFactor(train,key,target){const rows=train.filter(e=>Number.isFinite(e.features[key])).slice().sort((a,b)=>a.features[key]-b.features[key]);if(rows.length<20)return null;const q=p=>rows[Math.min(rows.length-1,Math.floor((rows.length-1)*p))].features[key];const cuts=[q(.2),q(.4),q(.6),q(.8)],bins=[[],[],[],[],[]];for(const e of rows){const v=e.features[key];let b=0;while(b<cuts.length&&v>cuts[b])b++;bins[b].push(e);}const base=train.filter(e=>e[target]).length/train.length;const rates=bins.map(g=>g.length?g.filter(e=>e[target]).length/g.length:base);return{key,cuts,rates,base};}
function binIndex(v,cuts){let b=0;while(b<cuts.length&&v>cuts[b])b++;return b;}
function fitModel(train,target){const models=FACTORS.map(k=>fitFactor(train,k,target)).filter(Boolean);if(!models.length)throw new Error(`No factor models for ${target}`);return{target,models,base:train.filter(e=>e[target]).length/train.length};}
function predict(model,e){const scores=[];for(const m of model.models){const v=e.features[m.key];if(!Number.isFinite(v))continue;scores.push(m.rates[binIndex(v,m.cuts)]);}return scores.length?mean(scores):model.base;}
function auc(scored,target){const pos=scored.filter(x=>x.e[target]),neg=scored.filter(x=>!x.e[target]);if(!pos.length||!neg.length)return null;let wins=0,total=0;for(const p of pos)for(const n of neg){wins+=p.score>n.score?1:p.score===n.score?.5:0;total++;}return wins/total;}
function terciles(scored,target){const s=scored.slice().sort((a,b)=>a.score-b.score),groups=[[],[],[]];for(let i=0;i<s.length;i++)groups[Math.min(2,Math.floor(i*3/s.length))].push(s[i]);const out=groups.map((g,i)=>({group:['low','mid','high'][i],samples:g.length,avg_score_pct:round(mean(g.map(x=>x.score))*100),actual_rate_pct:g.length?round(g.filter(x=>x.e[target]).length/g.length*100):null}));return{groups:out,high_low_spread_pp:out[2].actual_rate_pct!=null&&out[0].actual_rate_pct!=null?round(out[2].actual_rate_pct-out[0].actual_rate_pct):null};}
function brier(scored,target){return mean(scored.map(x=>(x.score-(x.e[target]?1:0))**2));}
function evaluate(train,test,target){const model=fitModel(train,target),scored=test.map(e=>({e,score:predict(model,e)})),t=terciles(scored,target);return{train_samples:train.length,test_samples:test.length,train_base_rate_pct:round(model.base*100),test_base_rate_pct:round(test.filter(e=>e[target]).length/test.length*100),auc:round(auc(scored,target)),brier:round(brier(scored,target)),terciles:t.groups,high_low_spread_pp:t.high_low_spread_pp};}
function fixedOos(events,oosStart){const trainEnd=shiftMonth(oosStart,-2),train=events.filter(e=>e.month<=trainEnd),test=events.filter(e=>e.month>=oosStart);return{oos_start_month:oosStart,embargo_month:shiftMonth(oosStart,-1),train_end_month:trainEnd,train_samples:train.length,test_samples:test.length,pb5:evaluate(train,test,'pb5'),pb10:evaluate(train,test,'pb10')};}
function quarterStarts(start,end){const out=[];let y=+start.slice(0,4),m=+start.slice(4,6);m=([1,4,7,10].find(q=>q>=m)||1);if(m===1&&+start.slice(4,6)>10)y++;for(;;){const s=`${y}${String(m).padStart(2,'0')}`;if(s>end)break;out.push(s);m+=3;if(m>12){m-=12;y++;}}return out;}
function walkForward(events,start,end){const first= start<'202501'?'202501':start,folds=[];for(const qs of quarterStarts(first,end)){const qe=[shiftMonth(qs,2),end].sort()[0],trainEnd=shiftMonth(qs,-2),embargo=shiftMonth(qs,-1),train=events.filter(e=>e.month<=trainEnd),test=events.filter(e=>e.month>=qs&&e.month<=qe);if(train.length<50||test.length<8)continue;folds.push({test_start_month:qs,test_end_month:qe,train_end_month:trainEnd,embargo_month:embargo,train_samples:train.length,test_samples:test.length,pb5:evaluate(train,test,'pb5'),pb10:evaluate(train,test,'pb10')});}
function sumTarget(target){const xs=folds.map(f=>f[target]);return{folds:xs.length,median_auc:round(median(xs.map(x=>x.auc))),avg_auc:round(mean(xs.map(x=>x.auc))),median_high_low_spread_pp:round(median(xs.map(x=>x.high_low_spread_pp))),positive_spread_fold_rate_pct:round(xs.filter(x=>x.high_low_spread_pp>0).length/xs.length*100),auc_ge_0_55_fold_rate_pct:round(xs.filter(x=>x.auc>=.55).length/xs.length*100)};}
return{folds,summary:{pb5:sumTarget('pb5'),pb10:sumTarget('pb10')}};}
function verdict(fixed,walk){function targetVerdict(k){const f=fixed[k],w=walk.summary[k];const strong=f.auc>=.60&&f.high_low_spread_pp>=15&&w.median_auc>=.57&&w.positive_spread_fold_rate_pct>=66.6667;const weak=f.auc>=.55&&f.high_low_spread_pp>=8&&w.positive_spread_fold_rate_pct>=50;return strong?'validated':weak?'promising_but_not_validated':'not_validated';}const pb5=targetVerdict('pb5'),pb10=targetVerdict('pb10'),routingReady=pb5==='validated'||pb10==='validated';return{pb5_status:pb5,pb10_status:pb10,routing_ready:routingReady,decision:routingReady?'At least one pullback target shows repeatable OOS separation; proceed to a routed-entry policy backtest, but do not promote directly to production.':'Current four-factor timing model does not show enough repeatable OOS separation to justify changing the 100% direct-entry baseline. Keep timing factors research-only and retain direct entry as the default.'};}
function fmt(v,s=''){return v==null?'NA':`${v}${s}`;}
function updateDoc(out){let doc=fs.readFileSync(DOC,'utf8');const f=out.fixed_oos,w=out.walk_forward.summary,c=out.conclusion;const status=x=>x==='validated'?'通過 OOS 驗證':x==='promising_but_not_validated'?'有潛力但未通過':'未通過 OOS 驗證';const section=`<!-- WALK_FORWARD_OOS_START -->\n## Round 5 — Timing Walk-forward / OOS 驗證\n\n研究問題：上一輪挑出的四個 timing 因子（\`pre20_vol_pct\`、\`pre5_return_pct\`、\`pre20_return_pct\`、\`dist_from_20d_high_pct\`）在未見資料上，是否真的能區分「容易回檔」與「不容易回檔」？\n\n方法：\n\n- 固定 OOS：\`${f.oos_start_month}\` 起為測試集。\n- 訓練資料截止 \`${f.train_end_month}\`，\`${f.embargo_month}\` 保留為 embargo，避免最近訊號的 20 日回檔標籤尚未成熟。\n- 模型只使用上述 4 個 timing 因子；每個因子僅依訓練集 quintile 回檔率形成分數，再對測試集評分。\n- 另外使用季度 expanding-window walk-forward，且每折都保留 1 個月 embargo。\n- 評估 AUC 與預測 high / low tercile 的實際回檔率差距。\n\n固定 OOS 結果：\n\n| Target | Train | OOS | OOS baseline | AUC | High-Low spread | 結論 |\n|---|---:|---:|---:|---:|---:|---|\n| -5% | ${f.pb5.train_samples} | ${f.pb5.test_samples} | ${fmt(f.pb5.test_base_rate_pct,'%')} | ${fmt(f.pb5.auc)} | ${fmt(f.pb5.high_low_spread_pp,'pp')} | **${status(c.pb5_status)}** |\n| -10% | ${f.pb10.train_samples} | ${f.pb10.test_samples} | ${fmt(f.pb10.test_base_rate_pct,'%')} | ${fmt(f.pb10.auc)} | ${fmt(f.pb10.high_low_spread_pp,'pp')} | **${status(c.pb10_status)}** |\n\nWalk-forward 穩定性：\n\n| Target | Folds | Median AUC | Avg AUC | Median high-low spread | 正 spread folds | AUC >= 0.55 folds |\n|---|---:|---:|---:|---:|---:|---:|\n| -5% | ${w.pb5.folds} | ${fmt(w.pb5.median_auc)} | ${fmt(w.pb5.avg_auc)} | ${fmt(w.pb5.median_high_low_spread_pp,'pp')} | ${fmt(w.pb5.positive_spread_fold_rate_pct,'%')} | ${fmt(w.pb5.auc_ge_0_55_fold_rate_pct,'%')} |\n| -10% | ${w.pb10.folds} | ${fmt(w.pb10.median_auc)} | ${fmt(w.pb10.avg_auc)} | ${fmt(w.pb10.median_high_low_spread_pp,'pp')} | ${fmt(w.pb10.positive_spread_fold_rate_pct,'%')} | ${fmt(w.pb10.auc_ge_0_55_fold_rate_pct,'%')} |\n\n本輪結論：\n\n> ${c.routing_ready?'**至少一個回檔 target 在 OOS / walk-forward 顯示可重複的辨識力；下一步可以做「依預測分流進場」的 OOS policy backtest，但目前仍不可直接升級 production。**':'**四個 timing 因子的 in-sample spread 尚未轉化成足夠穩定的 OOS 優勢；目前沒有證據支持取代 100% 訊號日直接進場。Timing 因子保留研究用途，不應因上一輪漂亮分桶而直接做進場 gate。**'}\n\n機器判定：\n\n- -5%：\`${c.pb5_status}\`\n- -10%：\`${c.pb10_status}\`\n- Routed-entry ready：\`${c.routing_ready}\`\n\nJSON：\`data_prediction_analysis/quarterly-financial-quality/two-stage-fundamental-quality-pullback-walk-forward.json\`\n<!-- WALK_FORWARD_OOS_END -->`;
const re=/<!-- WALK_FORWARD_OOS_START -->[\s\S]*?<!-- WALK_FORWARD_OOS_END -->/;doc=re.test(doc)?doc.replace(re,section):`${doc.trim()}\n\n---\n\n${section}\n`;const summaryLine=c.routing_ready?'8. **Timing 四因子至少一個 target 已通過 OOS / walk-forward 初步驗證；下一步應只做 routed-entry policy 的 OOS 回測，仍不可直接 production。**':'8. **Timing 四因子的 in-sample 辨識力未能穩定通過 OOS / walk-forward；目前維持 100% 訊號日直接進場為預設，timing 僅保留研究用途。**';if(doc.includes('7. 下一階段不應繼續微調固定分批比例')){doc=doc.replace(/7\. 下一階段不應繼續微調固定分批比例[^\n]*/,`7. 下一階段不應繼續微調固定分批比例，而應以 OOS 驗證決定 timing 是否值得進入分流策略。\n${summaryLine}`);}fs.writeFileSync(DOC,doc.endsWith('\n')?doc:`${doc}\n`);}
function main(argv=process.argv.slice(2)){const args=parseArgs(argv),start=args.get('start-month')||'202401',end=args.get('end-month')||'202606',oosStart=args.get('oos-start-month')||'202601';const loaded=collectEvents(start,end);if(loaded.events.length<80)throw new Error(`Too few events: ${loaded.events.length}`);const fixed=fixedOos(loaded.events,oosStart);if(fixed.train_samples<50||fixed.test_samples<15)throw new Error(`Insufficient fixed OOS split train=${fixed.train_samples} test=${fixed.test_samples}`);const walk=walkForward(loaded.events,start,end),conclusion=verdict(fixed,walk);const out={schema_version:1,dataset:'two_stage_fundamental_quality_pullback_walk_forward',generated_at:new Date().toISOString(),start_month:start,end_month:end,features:FACTORS,methodology:{status:'research_only',universe:'electronic FAS>=8 + latest-known FQ>=10',model:'training-only quintile conditional pullback rates averaged across four timing factors',fixed_oos:`${oosStart}..${end}`,embargo:'one full signal month immediately before each OOS test window is excluded from training',walk_forward:'expanding-window quarterly tests from 2025 onward',promotion_rule:'validated requires fixed OOS AUC>=0.60, high-low spread>=15pp, walk-forward median AUC>=0.57 and >=2/3 folds positive spread'},coverage:{candidate_events:loaded.events.length,diagnostics:loaded.diag},fixed_oos:fixed,walk_forward:walk,conclusion};fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(out,null,2)+'\n');updateDoc(out);console.log(JSON.stringify({output:path.relative(ROOT,OUTPUT),fixed_oos:fixed,walk_forward:walk.summary,conclusion},null,2));}
if(require.main===module){try{main();}catch(e){console.error(e.stack||e.message);process.exitCode=1;}}
