#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const SIGNAL_ROOT = path.join(ROOT, 'data_prediction_analysis', 'monthly-revenue', 'monthly-signals');
const REVENUE_ROOT = path.join(ROOT, 'data_mops_monthly_revenue');
const OUTPUT = path.join(SIGNAL_ROOT, 'industry-breakdown.json');
const HORIZONS = ['d5', 'd10', 'd20'];
const MIN_SAMPLES = 30;
const MIN_MONTHS = 3;

const mean = xs => { const a = xs.filter(Number.isFinite); return a.length ? a.reduce((s,v)=>s+v,0)/a.length : null; };
const round = (v,d=4) => Number.isFinite(v) ? Number(v.toFixed(d)) : null;
function readJson(file, fallback=null){ try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;} }
function parseArgs(argv){const m=new Map();for(let i=0;i<argv.length;i++){if(!argv[i].startsWith('--'))continue;m.set(argv[i].slice(2),argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true);}return m;}
function prevMonth(month,n=1){let y=Number(month.slice(0,4)),m=Number(month.slice(4,6));for(let i=0;i<n;i++){m--;if(m===0){m=12;y--;}}return `${y}${String(m).padStart(2,'0')}`;}
function loadRevenueHistory(){const months=fs.readdirSync(REVENUE_ROOT,{withFileTypes:true}).filter(e=>e.isDirectory()&&/^20\d{4}$/.test(e.name)).map(e=>e.name).sort();const byMonth=new Map(),byStock=new Map();for(const month of months){const p=readJson(path.join(REVENUE_ROOT,month,'monthly_revenue.json'),{}),map=new Map();for(const row of p.companies||[]){map.set(String(row.stock_code),row);if(!byStock.has(String(row.stock_code)))byStock.set(String(row.stock_code),new Map());byStock.get(String(row.stock_code)).set(month,row);}byMonth.set(month,map);}return {byMonth,byStock};}
function loadStudy(start,end){return fs.readdirSync(SIGNAL_ROOT).filter(n=>/^20\d{4}\.json$/.test(n)).map(n=>n.slice(0,6)).filter(m=>(!start||m>=start)&&(!end||m<=end)).sort().map(month=>({month,payload:readJson(path.join(SIGNAL_ROOT,`${month}.json`),{})}));}
function consecutive(stockMap,month,count){for(let i=0;i<count;i++){const r=stockMap?.get(prevMonth(month,i));if(!r||Number(r.yoy_pct)<20)return false;}return true;}
function revenueHigh3(stockMap,month){const vals=[];for(let i=0;i<3;i++){const r=stockMap?.get(prevMonth(month,i));if(!r||!Number.isFinite(Number(r.monthly_revenue_thousand_twd)))return false;vals.push(Number(r.monthly_revenue_thousand_twd));}return vals[0]===Math.max(...vals);}
const FACTORS=[
  {id:'yoy20_mom_positive',name:'YoY ≥20% + MoM >0',test:(e,row)=>Number(e.factors?.yoy_pct)>=20&&Number(e.factors?.mom_pct)>0},
  {id:'yoy20_revenue_high_3',name:'YoY ≥20% + 營收3月新高',test:(e,row,sm)=>Number(e.factors?.yoy_pct)>=20&&revenueHigh3(sm,e.revenue_month)},
  {id:'yoy20_consecutive_2',name:'連續2月 YoY ≥20%',test:(e,row,sm)=>consecutive(sm,e.revenue_month,2)},
  {id:'yoy20_consecutive_3',name:'連續3月 YoY ≥20%',test:(e,row,sm)=>consecutive(sm,e.revenue_month,3)},
];
function summarizeGroup(months,history,factor,horizon,industry){const allFactor=[],allIndustry=[],allMarket=[],monthly=[];for(const {month,payload} of months){const revMap=history.byMonth.get(month)||new Map();const complete=(payload.events||[]).filter(e=>e.returns?.[horizon]?.status==='complete');const market=complete.map(e=>e.returns[horizon]);const industryEvents=complete.filter(e=>(revMap.get(String(e.stock_code))?.industry||'未分類')===industry);const factorEvents=industryEvents.filter(e=>factor.test({...e,revenue_month:month},revMap.get(String(e.stock_code)),history.byStock.get(String(e.stock_code))));if(!factorEvents.length)continue;const fr=factorEvents.map(e=>e.returns[horizon]),ir=industryEvents.map(e=>e.returns[horizon]);const win=rs=>rs.length?rs.filter(r=>r.outperformed_market===true).length/rs.length*100:null;const ex=rs=>mean(rs.map(r=>Number(r.excess_return_pct)));monthly.push({month,samples:fr.length,industry_samples:ir.length,market_samples:market.length,factor_win_rate:round(win(fr)),industry_win_rate:round(win(ir)),market_win_rate:round(win(market)),industry_win_uplift_pp:round(win(fr)-win(ir)),market_win_uplift_pp:round(win(fr)-win(market)),factor_avg_excess_pct:round(ex(fr)),industry_avg_excess_pct:round(ex(ir)),market_avg_excess_pct:round(ex(market)),industry_excess_uplift_pct:round(ex(fr)-ex(ir)),market_excess_uplift_pct:round(ex(fr)-ex(market))});allFactor.push(...fr);allIndustry.push(...ir);allMarket.push(...market);}
const samples=allFactor.length,coveredMonths=monthly.length;const credible=samples>=MIN_SAMPLES&&coveredMonths>=MIN_MONTHS;if(!samples)return null;const win=rs=>rs.length?rs.filter(r=>r.outperformed_market===true).length/rs.length*100:null;const ex=rs=>mean(rs.map(r=>Number(r.excess_return_pct)));const posIndustryWin=monthly.filter(m=>m.industry_win_uplift_pp>0).length/coveredMonths*100;const posIndustryEx=monthly.filter(m=>m.industry_excess_uplift_pct>0).length/coveredMonths*100;const score=credible?0.35*Math.max(0,Math.min(100,50+(win(allFactor)-win(allIndustry))*5))+0.30*Math.max(0,Math.min(100,50+(ex(allFactor)-ex(allIndustry))*20))+0.25*((posIndustryWin+posIndustryEx)/2)+0.10*Math.min(100,Math.log10(Math.max(samples,1))/3*100):null;return {factor_id:factor.id,factor_name:factor.name,industry,horizon,samples,covered_months:coveredMonths,credible,min_samples:MIN_SAMPLES,min_months:MIN_MONTHS,factor_relative_win_rate:round(win(allFactor)),industry_relative_win_rate:round(win(allIndustry)),market_relative_win_rate:round(win(allMarket)),industry_win_uplift_pp:round(win(allFactor)-win(allIndustry)),market_win_uplift_pp:round(win(allFactor)-win(allMarket)),factor_avg_excess_pct:round(ex(allFactor)),industry_avg_excess_pct:round(ex(allIndustry)),market_avg_excess_pct:round(ex(allMarket)),industry_excess_uplift_pct:round(ex(allFactor)-ex(allIndustry)),market_excess_uplift_pct:round(ex(allFactor)-ex(allMarket)),positive_industry_win_uplift_month_rate:round(posIndustryWin),positive_industry_excess_uplift_month_rate:round(posIndustryEx),industry_research_score:round(score),monthly};}
function main(argv=process.argv.slice(2)){const args=parseArgs(argv),start=args.get('start-month')||null,end=args.get('end-month')||null,history=loadRevenueHistory(),months=loadStudy(start,end);if(!months.length)throw new Error('No study months found');const industries=[...new Set([...history.byMonth.values()].flatMap(m=>[...m.values()].map(r=>r.industry||'未分類')))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));const rows=[];for(const h of HORIZONS)for(const f of FACTORS)for(const industry of industries){const r=summarizeGroup(months,history,f,h,industry);if(r)rows.push(r);}const out={schema_version:1,dataset:'mops_monthly_revenue_industry_breakdown',generated_at:new Date().toISOString(),start_month:months[0].month,end_month:months.at(-1).month,methodology:{factors:'four prioritized YoY>=20% candidates',primary_baseline:'same-industry observations in same months and horizon',secondary_baseline:'all listed-stock observations in same months and horizon',credibility_rule:`samples >= ${MIN_SAMPLES} and covered_months >= ${MIN_MONTHS}`,caution:'industry research only; low-credibility rows are retained but excluded from ranking'},horizons:HORIZONS,factors:FACTORS.map(({id,name})=>({id,name})),industries,rows};fs.writeFileSync(OUTPUT,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({output:path.relative(ROOT,OUTPUT),rows:rows.length,credible_rows:rows.filter(r=>r.credible).length},null,2));}
if(require.main===module){try{main();}catch(e){console.error(e.stack||e.message);process.exitCode=1;}}
module.exports={FACTORS,consecutive,revenueHigh3,summarizeGroup};
