'use strict';
const fs=require('node:fs'),path=require('node:path');
const {DAILY_GAINERS_AI_CONTRACT:CONTRACT,isLatestNews,isLatestPublished}=require('./lib/daily_gainers_ai_contract');
const ROOT=path.resolve(__dirname,'..'),DATA=path.join(ROOT,'data_daily_gain_over_5'),TAX=path.join(ROOT,CONTRACT.market_summary.theme_taxonomy_path);
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));function assert(c,m){if(!c)throw new Error(`Invalid daily gainers market summary: ${m}`)}function count(v,l,max){assert(Number.isInteger(v)&&v>=0,`${l} must be non-negative integer`);if(Number.isFinite(max))assert(v<=max,`${l} exceeds stock_count`)}function percent(v,l){const n=Number(v);assert(Number.isFinite(n)&&n>=0&&n<=100,`${l} must be 0..100`)}
function validate(s,raw,date){const c=CONTRACT.market_summary;assert(s.schema_version===c.schema_version,'schema_version mismatch');assert(s.methodology_version===c.methodology_version,'methodology_version mismatch');assert(s.contract_version===CONTRACT.contract_version,'contract_version mismatch');assert(s.target_date===date&&raw.target_date===date,'target_date mismatch');assert(c.allowed_statuses.includes(s.status),'invalid status');assert(c.allowed_summary_stages.includes(s.summary_stage),'invalid summary_stage');for(const f of c.required_fields)assert(Object.hasOwn(s,f),`missing ${f}`);
 const rows=Array.isArray(raw.stocks)?raw.stocks:[],stockCount=rows.length,rawCodes=rows.map(x=>String(x.code));assert(new Set(rawCodes).size===rawCodes.length,'raw codes duplicate');for(const r of rows)assert(Number.isFinite(Number(r.change_pct))&&Number(r.change_pct)>=5,`bad change_pct ${r.code}`);const b=s.breadth||{};assert(b.stock_count===stockCount,'breadth stock_count mismatch');for(const k of ['gain_5_to_7_count','gain_7_to_9_5_count','gain_9_5_plus_count'])count(b[k],k,stockCount);assert(b.gain_5_to_7_count+b.gain_7_to_9_5_count+b.gain_9_5_plus_count===stockCount,'gain buckets mismatch');
 if(s.previous_date!=null){assert(/^\d{8}$/.test(s.previous_date)&&s.previous_date<date,'invalid previous_date');assert(s.previous_date===String(raw.previous_date||''),'previous_date differs raw');const pf=path.join(DATA,`${s.previous_date}.json`);if(s.source_lineage.previous_raw.available){assert(fs.existsSync(pf),'previous_raw missing');const p=read(pf);assert(Array.isArray(p.stocks),'previous stocks missing');assert(b.previous_day_stock_count===p.stocks.length&&b.stock_count_change===stockCount-p.stocks.length,'previous breadth mismatch')}else assert(b.previous_day_stock_count===null&&b.stock_count_change===null,'missing previous needs null counts')}
 const tax=read(TAX),ids=new Set((tax.themes||[]).map(x=>x.id)),seen=new Set();let themed=0;for(const t of s.theme_summary?.theme_ranking||[]){assert(ids.has(t.theme_id),`unknown theme ${t.theme_id}`);assert(!seen.has(t.theme_id),`duplicate theme ${t.theme_id}`);seen.add(t.theme_id);count(t.stock_count,'theme stock_count',stockCount);count(t.near_limit_up_count,'near_limit_up_count',t.stock_count);percent(t.share_pct,'theme share');for(const x of t.representative_stocks||[])assert(rawCodes.includes(String(x)),`theme stock outside raw ${x}`);themed+=t.stock_count}count(s.theme_summary.themed_stock_count,'themed_stock_count',stockCount);count(s.theme_summary.unclassified_stock_count,'unclassified_stock_count',stockCount);assert(s.theme_summary.themed_stock_count+s.theme_summary.unclassified_stock_count===stockCount,'theme coverage mismatch');assert(themed===s.theme_summary.themed_stock_count,'theme ranking sum mismatch');for(const k of ['theme_coverage_pct','top_1_theme_share_pct','top_3_theme_share_pct'])percent(s.theme_summary[k],k);assert(c.allowed_market_regimes.includes(s.theme_summary.market_structure),'bad market_structure');assert(s.market_context?.regime===s.theme_summary.market_structure,'market_context mismatch');
 const cat=s.catalyst_coverage||{};for(const k of ['direct','corroborated','circumstantial','none','unavailable','public_catalyst_count'])count(cat[k],`catalyst ${k}`,stockCount);assert(cat.direct+cat.corroborated+cat.circumstantial+cat.none+cat.unavailable===stockCount,'catalyst buckets mismatch');assert(cat.public_catalyst_count===cat.direct+cat.corroborated,'public catalyst mismatch');percent(cat.public_catalyst_coverage_pct,'public catalyst pct');const causeTotal=Object.entries(cat.cause_type_counts||{}).reduce((sum,[k,v])=>{assert(CONTRACT.cause_types.includes(k),`bad cause ${k}`);count(v,`cause ${k}`,stockCount);return sum+v},0);assert(causeTotal===stockCount-cat.unavailable,'cause coverage mismatch');
 const f=s.funding_summary||{};assert(c.coverage_statuses.includes(f.coverage_status),'bad funding coverage');for(const k of ['available_stock_count','institutional_available_stock_count','margin_available_stock_count','institutional_support_count','institutional_opposition_count','margin_increase_count','margin_decrease_count'])count(f[k],`funding ${k}`,stockCount);if(s.summary_stage==='news_theme'){assert(s.status==='preliminary','news stage must be preliminary');assert(f.coverage_status==='missing'&&f.available_stock_count===0,'news stage must not synthesize funding')}if(s.summary_stage==='full_synthesis')assert(s.status==='final','full_synthesis must be final');
 const cov=s.coverage||{};for(const k of ['overall','raw','previous_raw','news','facts','analysis','funding'])assert(c.coverage_statuses.includes(cov[k]),`bad coverage.${k}`);assert(cov.raw==='complete','raw must complete');assert(cov.funding===f.coverage_status,'funding coverage mismatch');count(cov.analyzed_stock_count,'analyzed_stock_count',stockCount);assert(cov.raw_stock_count===stockCount,'raw_stock_count mismatch');assert(s.source_lineage?.raw?.path===`data_daily_gain_over_5/${date}.json`&&s.source_lineage.raw.available===true,'raw lineage mismatch');assert(s.source_lineage?.news?.path===`data_daily_gain_over_5/analysis-news/${date}.json`,'news lineage mismatch');assert(s.source_lineage?.analysis?.path===`data_daily_gain_over_5/analysis/${date}.json`,'analysis lineage mismatch');assert(s.source_lineage?.facts?.path===`data_daily_gain_over_5/analysis-facts/${date}.json`,'facts lineage mismatch');
 if(s.summary_stage==='news_theme'&&cov.news==='complete'){const nf=path.join(DATA,'analysis-news',`${date}.json`);assert(fs.existsSync(nf),'news file missing');const p=read(nf);assert(isLatestNews(p),'news not latest contract');assert((p.analyses||[]).map(x=>String(x.code)).join(',')===rawCodes.join(','),'news coverage/order mismatch');assert(cov.analyzed_stock_count===stockCount,'news complete must cover all')}
 if(s.status==='final'){assert(cov.analysis==='complete'&&cov.analyzed_stock_count===stockCount,'final coverage incomplete');const af=path.join(DATA,'analysis',`${date}.json`);assert(fs.existsSync(af),'final analysis missing');const p=read(af);assert(isLatestPublished(p),'final analysis not latest');assert((p.analyses||[]).map(x=>String(x.code)).join(',')===rawCodes.join(','),'final coverage/order mismatch')}
 assert(typeof s.headline==='string'&&s.headline.trim(),'headline required');assert(typeof s.market_summary==='string'&&s.market_summary.trim(),'market_summary required');assert(Array.isArray(s.risk_signals),'risk_signals array required');assert(Array.isArray(s.next_day_watch)&&s.next_day_watch.length,'next_day_watch required');return true}
function main(){const a=process.argv.slice(2);if(a[0]==='--self-test'){console.log('validate_daily_gainers_market_summary self-test passed');return}const i=a.indexOf('--date'),date=i>=0?a[i+1]:'';assert(/^\d{8}$/.test(date),'--date must be YYYYMMDD');const rf=path.join(DATA,`${date}.json`),sf=path.join(DATA,'market-summary',`${date}.json`);assert(fs.existsSync(rf)&&fs.existsSync(sf),'raw or summary missing');validate(read(sf),read(rf),date);console.log(`Validated daily gainers market summary: ${date}`)}if(require.main===module)main();module.exports={validateSummary:validate};
